version: '3'

volumes: 
  postgres_data: {}

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: {{ cookiecutter.project_slug }}_django:latest
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - POSTGRES_DB={{ cookiecutter.project_slug }}
      - POSTGRES_PASSWORD={{ cookiecutter.project_slug }}
      - POSTGRES_USER={{ cookiecutter.project_slug }}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
  
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # ports:
    #   - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB={{ cookiecutter.project_slug }}
      - POSTGRES_USER={{ cookiecutter.project_slug }}
      - POSTGRES_PASSWORD={{ cookiecutter.project_slug }}
