name: Test Django Template

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  full_test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # or any other version you'd like to test against

    - name: Install cookiecutter
      run: pip install cookiecutter

    - name: Install dependencies 
      run: sudo apt-get update && sudo apt-get install -y libpq-dev

    - name: Run shell tests
      run: bash tests/test_template.sh
  

